version: "2"

networks:
  custom:
    driver: bridge

services:

  proxy:
    image: h3nrik/nginx-ldap:1.11.3
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - custom
    ports:
      - "8080:8080"

  openldap:
    container_name: openldap
    build: ./openldap
    networks:
      - custom
    environment:
      - LDAP_ORGANISATION=MVP
      - LDAP_DOMAIN=mvp.org
      - LDAP_ADMIN_PASSWORD=admin
  
  jenkins:
    build: jenkins_master/
    container_name: jenkins
    networks:
      - custom
    environment:
      - JENKINS_OPTS=--prefix=/jenkins

  jenkins_slave:
    build: jenkins_slave/
    container_name: jenkins_slave
    networks:
      - custom
    depends_on:
      - jenkins
    environment:
      - "SWARM_MASTER=http://jenkins:8080/jenkins/"
      - "SLAVE_EXECUTORS=2"
      - "SLAVE_DESCRIPTION=test"
      - "SWARM_USER=test"
      - "SWARM_PASSWORD=t3st"
      - "SLAVE_NAME=test"
      - "SLAVE_LABELS=test"
      - "SLAVE_MODE=exclusive"